apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: rubyhello
  name: rubyhello
spec:
  replicas: 1
  selector:
    app: rubyhello
    deploymentconfig: rubyhello
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: rubyhello
        deploymentconfig: rubyhello
    spec:
      containers:
        - image: openshift/origin-ruby-sample
          imagePullPolicy: Always
          name: rubyhello
          ports:
            - containerPort: 8080
              protocol: TCP
      securityContext: {}
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - helloworld
        from:
          kind: ImageStreamTag
          name: origin-ruby-sample:latest
      type: ImageChange
